### ISSUE TITLE
Setup question

### ISSUE THREAD

**Issue by dysl357085918** [ilcato/homebridge-ifttt#22]
[2017-5-23 18:06:57] Loaded config.json with 1 accessories and 1 platforms.
[2017-5-23 18:06:57] ---
[2017-5-23 18:06:58] Loading 1 platforms...
[2017-5-23 18:06:58] [IFTTT] Initializing IFTTT platform...
[2017-5-23 18:06:58] [IFTTT] Loading accessories...
/usr/lib/node_modules/homebridge-ifttt/index.js:88
	  this.IFTTTaccessories.map(function(s) {
	                        ^

TypeError: this.IFTTTaccessories.map is not a function
    at Object.accessories (/usr/lib/node_modules/homebridge-ifttt/index.js:88:26)
    at Server._loadPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:354:20)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:298:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

**Comment by ilcato** [comment]
which version of node.js do you have?

**Comment by dysl357085918** [comment]
v6.10.0

**Comment by ilcato** [comment]
are you sure that you are using the latest version of the IFTTT plugin? It should be 0.2.2

**Comment by dysl357085918** [comment]
i solved it.
