### ISSUE TITLE
Could there be an issue with 'stateful'

### ISSUE THREAD

**Issue by omriavital** [ilcato/homebridge-ifttt#37]
Here is the config setup of my ifttt:
"platforms": [
        {
            "platform": "IFTTT",
            "name": "IFTTT",
            "makerkey": "----",
            "accessories": [
                {
                    "name": "Wyze Cam Alerts",
                    "buttons": [
                        {
                            "triggerOn": "enable_wyze",
                            "triggerOff": "disable_wyze",
                            "stateful": true
                        }
                    ]
                }
            ]
        },

Suddenly today, when switching the "Wyze Cam Alerts" switch on - homebridge crashes.

Here's the log:
0|homebridge  | TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
0|homebridge  |     at Hash.update (internal/crypto/hash.js:58:11)
0|homebridge  |     at md5 (/home/pi/.npm-global/lib/node_modules/homebridge-ifttt/node_modules/node-persist/src/local-storage.js:40:41)
0|homebridge  |     at LocalStorage.persistKeySync (/home/pi/.npm-global/lib/node_modules/homebridge-ifttt/node_modules/node-persist/src/local-storage.js:467:43)
0|homebridge  |     at LocalStorage.setItemSync (/home/pi/.npm-global/lib/node_modules/homebridge-ifttt/node_modules/node-persist/src/local-storage.js:255:14)
0|homebridge  |     at IFTTTPlatform.<anonymous> (/home/pi/.npm-global/lib/node_modules/homebridge-ifttt/index.js:221:22)
0|homebridge  |     at Characteristic.On.emit (events.js:198:13)
0|homebridge  |     at Characteristic.On.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
0|homebridge  |     at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
0|homebridge  |     at Array.forEach (<anonymous>:null:null)
0|homebridge  |     at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
0|homebridge  |     at HAPServer.emit (events.js:198:13)
0|homebridge  |     at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
0|homebridge  |     at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
0|homebridge  |     at IncomingMessage.emit (events.js:198:13)
0|homebridge  |     at endReadableNT (_stream_readable.js:1145:12)
0|homebridge  |     at process._tickCallback (internal/process/next_tick.js:63:19)
0|homebridge  | [10/1/2019, 12:51:26 PM] TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
0|homebridge  |     at Hash.update (internal/crypto/hash.js:58:11)
0|homebridge  |     at md5 (/home/pi/.npm-global/lib/node_modules/homebridge-ifttt/node_modules/node-persist/src/local-storage.js:40:41)
0|homebridge  |     at LocalStorage.persistKeySync (/home/pi/.npm-global/lib/node_modules/homebridge-ifttt/node_modules/node-persist/src/local-storage.js:467:43)
0|homebridge  |     at LocalStorage.setItemSync (/home/pi/.npm-global/lib/node_modules/homebridge-ifttt/node_modules/node-persist/src/local-storage.js:255:14)
0|homebridge  |     at IFTTTPlatform.<anonymous> (/home/pi/.npm-global/lib/node_modules/homebridge-ifttt/index.js:221:22)
0|homebridge  |     at Characteristic.On.emit (events.js:198:13)
0|homebridge  |     at Characteristic.On.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
0|homebridge  |     at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
0|homebridge  |     at Array.forEach (<anonymous>:null:null)
0|homebridge  |     at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
0|homebridge  |     at HAPServer.emit (events.js:198:13)
0|homebridge  |     at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
0|homebridge  |     at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
0|homebridge  |     at IncomingMessage.emit (events.js:198:13)
0|homebridge  |     at endReadableNT (_stream_readable.js:1145:12)
0|homebridge  |     at process._tickCallback (internal/process/next_tick.js:63:19)

Removing the "stateful: true" parameter, solved it.  But I do wish for the state to be saved...

Until now: was working fine

What I did recently: some apt update/upgrades

Any clue?

**Comment by ilcato** [comment]
@omriavital can you try with the latest version?

**Comment by CooperCGN** [comment]
Hello, doesn’t work for me with the latest version too. Using it on a fresh setup of homebridge with the official homebridge image.

**Comment by Niklas31** [comment]
I have a problem with Stateful as well. It ignores whatever I defined and simply keeps the accessory on. No matter if it was set to true or false

**Comment by fadelguy** [comment]
I have the same problem with Stateful , the accessory button stays on
